apiVersion: v1
kind: Pod
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  containers:
  - name: redis
    image: redis:6.2
    command:
      - "redis-server"
      - "--replicaof"
      - "redis-master"
      - "6379"
    ports:
    - containerPort: 6379
