apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: redis:6.2
        command:
          - "redis-server"
          - "--replicaof"
          - "redis-master"
          - "6379"
        ports:
        - containerPort: 6379
